version: '2'
services:
    php:
     image: php:fpm
     container_name: app-php-fpm
     volumes:
         - ./site:/var/www/html/web
    nginx-proxy:
     image: jwilder/nginx-proxy
     container_name: nginx-proxy
     ports:
         - "80:80"
     volumes:
         - /var/run/docker.sock:/tmp/docker.sock:ro
    paypal:
     image: dmitrovskiy/docker-nginx-php-fpm:1.0.0-alpine
     container_name: app-paypal
     environment:
         - VIRTUAL_HOST=paypal.site.org
     volumes:
         - ./site/paypal:/var/www/html/web
    reports:
     image: dmitrovskiy/docker-nginx-php-fpm:1.0.0-alpine
     container_name: app-reports
     environment:
         - VIRTUAL_HOST=reports.site.org
     volumes:
         - ./site/reports:/var/www/html/web
    invoice:
     image: dmitrovskiy/docker-nginx-php-fpm:1.0.0-alpine
     container_name: app-invoice
     environment:
         - VIRTUAL_HOST=invoice.site.org
     volumes:
         - ./site/invoice:/var/www/html/web
    postgresql_test:
     image: postgres
     container_name: postgresql_test
     ports:
         - "5432:5432"
     environment:
         - "POSTGRES_USER=postgres"
         - "POSTGRES_PASSWORD=1q2w3e4r"
         - "POSTGRES_DB=postgres"
     volumes:
         - ./srv/docker/postgresql/data:/var/lib/postgresql/data
         - ./schema:/home/postgres/schema
    schema_setup:
        build: ./schema
        environment:
         - "POSTGRES_USER=postgres"
         - "POSTGRES_PASSWORD=1q2w3e4r"
         - "POSTGRES_DB=postgres"
         - "PGHOST=target_service"
         - "PGPASSWORD=1q2w3e4r"
        links:
         - postgresql_test:target_service
        volumes:
         - ./schema:/schema
        depends_on:
         - postgresql_test
        #command: ./wfi/wait-for-it.sh target_service:5432 -s -t 600  -- ./create_schema.sh my_yacht db.sql 
        command: /schema/start.sh
    postgrest_test:
     build: .
     container_name: postgrest_test
     environment:
         - "POSTGREST_VERSION=0.3.2.0"
         - "POSTGREST_DBHOST=postgresql_test"
         - "POSTGREST_DBPORT=5432"
         - "POSTGREST_DBNAME=postgres"
         - "POSTGREST_DBUSER=postgres"
         - "POSTGREST_SCHEMA=my_yacht"
         - "POSTGREST_DBPASS=1q2w3e4r"
         - "POSTGREST_PORT=80"
         - VIRTUAL_HOST=site.org
     links:
         - postgresql_test:postgresql_test
     depends_on:
         - postgresql_test
